name: Build TikTokDownloader EXE

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        if exist requirements.txt (pip install -r requirements.txt)

    - name: Build .exe with PyInstaller
      run: |
        pyinstaller --onefile --noconsole --icon=icon.ico gui.py

    - name: Upload EXE artifact
      uses: actions/upload-artifact@v3
      with:
        name: TikTokDownloader
        path: dist/gui.exe
